/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.doctor;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

import com.raxit.hibernate.DoctorPOJO;
import com.raxit.hibernate.HibernateUtil;
import com.raxit.hibernate.PaitentPOJO;

/** 
 * MyEclipse Struts
 * Creation date: 09-22-2013
 * 
 * XDoclet definition:
 * @struts.action path="/doctorLogin" name="doctorLoginForm" input="doctor/doctorLogin.jsp" scope="request" validate="true"
 */
public class DoctorLoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DoctorLoginForm doctorLoginForm = (DoctorLoginForm) form;// TODO Auto-generated method stub
		
		String _department = doctorLoginForm.getDepartment();
		String uuid = doctorLoginForm.getUid();
		
		
		String name =null;
		String  email =null;
		String desgnation =null;
		String department=null;
		String phoneno=null;
		
		
		SessionFactory session = HibernateUtil.getSessionFactory();
		  Session sess = session.getCurrentSession();
		  
		  sess.beginTransaction();
		  	
	  		Query q  =	sess.createQuery("from DoctorPOJO where  Department = :d and UUID = :u");
	  		q.setString("d", _department);
	  		q.setString("u", uuid);
	  		
	  		List<DoctorPOJO> detail =(List<DoctorPOJO>)q.list();
	  		sess.getTransaction().commit();
		
	  		for(DoctorPOJO heli1 : detail)
	  		{
	  			name = heli1.getName();
	  			email = heli1.getEmail();
	  			desgnation = heli1.getDesignation();
	  			department = heli1.getDepartment();
	  			phoneno = heli1.getContact_No();
	  			  			
	  		}
	  		
	  		HttpSession doctor = request.getSession();
		
	  		if(detail.size()>0)
		     {
		    	doctor.setAttribute("Name", name);
		    	doctor.setAttribute("Email",email);
		    	doctor.setAttribute("Designation",desgnation );
		    	doctor.setAttribute("Department",department );
		    	doctor.setAttribute("Contact_No",phoneno );
		    	doctor.setAttribute("UUID",uuid);
		    	 
		    	 return mapping.findForward("success");
		     }
		
		
		     String e ="Login Error...try again";
				request.getSession().setAttribute("Login_Error",e);
				System.out.println("Loginerror");
				return mapping.findForward("failure");
		
		
		
	}
}