/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.doctor;

import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.raxit.hibernate.HibernateUtil;
import com.raxit.hibernate.PaitentPOJO;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2013
 * 
 * XDoclet definition:
 * @struts.action path="/doctorPrescription1" name="doctorPrescription1Form" input="doctor/doctorPrescription1.jsp" scope="request" validate="true"
 */
public class DoctorPrescription1Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DoctorPrescription1Form doctorPrescription1Form = (DoctorPrescription1Form) form;// TODO Auto-generated method stub
		
		String _insuranceno = doctorPrescription1Form.getInsuranceno();
		//String status = "1";
		String _status = null;
		Session sess = HibernateUtil.getSessionFactory().openSession();
		Transaction t = sess.beginTransaction();
		
		Query q = sess.createQuery("From PaitentPOJO where insuranceno = :i");
		q.setString("i", _insuranceno);
		
		
		
		
		List<PaitentPOJO> p = (List<PaitentPOJO>)q.list();
		
		for(PaitentPOJO e1 : p)
		{
			_status=e1.getStatus();
		}
		
		if(_status != null && _status.equals("1"))
		{
			return mapping.findForward("failure");
		}
		
		HttpSession doctor = request.getSession();
		doctor.setAttribute("insuranceno", _insuranceno);
		
		return mapping.findForward("success");
	}
}