/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.doctor;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.insurance.table.InsurancePojo;
import com.raxit.hibernate.HibernateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-22-2013
 * 
 * XDoclet definition:
 * @struts.action path="/searchHistory" name="searchHistoryForm" input="doctor/searchHistory.jsp" scope="request" validate="true"
 */
public class SearchHistoryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		SearchHistoryForm searchHistoryForm = (SearchHistoryForm) form;// TODO Auto-generated method stub
		
		String _search = searchHistoryForm.getSearch();
		String _value = searchHistoryForm.getValue();
		
		HttpSession doctor = request.getSession();
		String _uuid = (String)doctor.getAttribute("UUID");
		
		System.out.println(_uuid);
		
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction tr = session.beginTransaction();
		
		if(_search.equals("Name"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where name = :v AND uuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Email"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where email = :v AND uuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Gender"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where gender = :v AND uuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Policy"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where policy = :v AND uuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Phoneno"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where phoneno = :v AND uuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("AdmitDate"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where admitdate = :v AND uuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("DischargeDate"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where dischargedate = :v AND uuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		Query q = session.createQuery( "From PrescriptionPOJO where insuranceno = :v AND uuid = :u ");
		q.setString("v",_value);
		q.setString("u",_uuid);
		
		List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
		request.getSession().setAttribute("data", check);
		
		System.out.println("search complete...");
		
		
		return mapping.findForward("success");
	}
}