/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.doctor;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.raxit.hibernate.HibernateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-28-2013
 * 
 * XDoclet definition:
 * @struts.action path="/search_AppointmentRequest" name="search_AppointmentRequestForm" input="doctor/search_AppointmentRequest.jsp" scope="request" validate="true"
 */
public class Search_AppointmentRequestAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Search_AppointmentRequestForm search_AppointmentRequestForm = (Search_AppointmentRequestForm) form;// TODO Auto-generated method stub
		
		String _search = search_AppointmentRequestForm.getSearch();
		String _value = search_AppointmentRequestForm.getValue();
		
		HttpSession doctor = request.getSession();
		String _uuid = (String)doctor.getAttribute("UUID");
		
		System.out.println(_uuid);
		
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction tr = session.beginTransaction();
		
		if(_search.equals("PaitentName"))
		{
			Query q = session.createQuery( "From AppointmentsPOJO where name = :v AND doctoruuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Date"))
		{
			Query q = session.createQuery( "From AppointmentsPOJO where date = :v AND doctoruuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
			
		}
		else if(_search.equals("Time"))
		{
			Query q = session.createQuery( "From AppointmentsPOJO where time = :v AND doctoruuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
			
		}
		else if(_search.equals("Email"))
		{
			Query q = session.createQuery( "From AppointmentsPOJO where email = :v AND doctoruuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
			
		}
		
			Query q = session.createQuery( "From AppointmentsPOJO where insuranceno = :v AND doctoruuid = :u ");
			q.setString("v",_value);
			q.setString("u",_uuid);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
			
		
	}
}