/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.raxit.hibernate.HibernateUtil;
import com.sanjivni.admit.AdmitedPaitentForm;
import com.sanjivni.doctor.PrescriptionPOJO;

/** 
 * MyEclipse Struts
 * Creation date: 09-23-2013
 * 
 * XDoclet definition:
 * @struts.action path="/admitedPaitent" name="admitedPaitentForm" input="admin/admitedPaitent.jsp" scope="request" validate="true"
 */
public class AdmitedPaitentAction extends Action {
	/*
	 * Generated Methods
	 */

	
	

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdmitedPaitentForm admitedPaitentForm = (AdmitedPaitentForm) form;// TODO Auto-generated method stub
		
		
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction tr = session.beginTransaction();
		
		Query q = session.createQuery( "From PaitentPOJO where Status != :s ");
		q.setString("s", "1");
		
		
		List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
		request.getSession().setAttribute("data", check);
		
		//System.out.println("search complete...");
		
		
		return mapping.findForward("success");
		
		
		
	}
}