/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.admin;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2013
 * 
 * XDoclet definition:
 * @struts.form name="adminLoginForm"
 */
public class AdminLoginForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	private String adminloginid;
	private String adminpasswd;
	
	
	
	
	
	
	public String getAdminloginid() {
		return adminloginid;
	}

	public void setAdminloginid(String adminloginid) {
		this.adminloginid = adminloginid;
	}

	public String getAdminpasswd() {
		return adminpasswd;
	}

	public void setAdminpasswd(String adminpasswd) {
		this.adminpasswd = adminpasswd;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}