/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.insurance.table.InsurancePojo;
import com.raxit.hibernate.DoctorPOJO;
import com.raxit.hibernate.HibernateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-20-2013
 * 
 * XDoclet definition:
 * @struts.action path="/displayDoct" name="displayDoctForm" input="admin/displayDoct.jsp" scope="request" validate="true"
 */
public class DisplayDoctAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DisplayDoctForm displayDoctForm = (DisplayDoctForm) form;// TODO Auto-generated method stub
		
		String _search = displayDoctForm.getSearch();
		String _value = displayDoctForm.getValue();
		
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction tr = session.beginTransaction();
		
		if(_search.equals("Name"))
		{
			Query q = session.createQuery( "From DoctorPOJO where Name = :v");
			q.setString("v",_value);
			
			List<DoctorPOJO> check = (List<DoctorPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		if(_search.equals("Email"))
		{
			Query q = session.createQuery( "From DoctorPOJO where Email = :v");
			q.setString("v",_value);
			
			List<DoctorPOJO> check = (List<DoctorPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		if(_search.equals("Department"))
		{
			Query q = session.createQuery( "From DoctorPOJO where Department = :v");
			q.setString("v",_value);
			
			List<DoctorPOJO> check = (List<DoctorPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		if(_search.equals("Contact_No"))
		{
			Query q = session.createQuery( "From DoctorPOJO where Contact_No = :v");
			q.setString("v",_value);
			
			List<DoctorPOJO> check = (List<DoctorPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		Query q = session.createQuery( "From DoctorPOJO where Designation = :v");
		q.setString("v",_value);
		
		List<DoctorPOJO> check = (List<DoctorPOJO>)q.list();
		request.getSession().setAttribute("data", check);
		
		System.out.println("search complete...");
		
		
		return mapping.findForward("success");
		
	}
}