/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.admin;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.transaction.Transaction;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;

import com.raxit.hibernate.DoctorPOJO;
import com.raxit.hibernate.HibernateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 08-07-2013
 * 
 * XDoclet definition:
 * @struts.action path="/displayHeli" name="displayHeliForm" input="/admin/displayHeli.jsp" scope="request" validate="true"
 */
public class DisplayHeliAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DisplayHeliForm displayHeliForm = (DisplayHeliForm) form;// TODO Auto-generated method stub
		org.hibernate.Session sess = HibernateUtil.getSessionFactory().openSession();
		org.hibernate.Transaction tr = sess.beginTransaction();

		

		//String SQL_STRING = "FROM DoctorPOJO";
		//Query query = sess.createQuery(SQL_STRING);
		//ArrayList list = (ArrayList) query.list();
		List list = sess.createQuery("FROM DoctorPOJO").list();
		request.getSession().setAttribute("data", list);
		Iterator itr = list.iterator();
	    /*  while(itr.hasNext()){
	        DoctorPOJO doc = (DoctorPOJO) itr.next();
	        System.out.print("--------------------");
	        System.out.print("id: "+ doc.getId());
	        System.out.print(" Name: "+ doc.getName());
	        System.out.print(" dep: "+ doc.getDepartment());
	       System.out.print(" timingsfrom: "+ doc.getTimingsFrom());
	       System.out.print(" timingsto: "+ doc.getTimingsTo());
	       System.out.print(" contactno: "+ doc.getContact_No());
	       System.out.print("--------------------");
	        System.out.println();
	      }*/
	      tr.commit();
		
		
		
		//request.getSession().setAttribute("data", list);
		
		//sess.getTransaction().commit();
		//HttpSession session=request.getSession(true);
		/*String ss=(String) session.getAttribute("name");
		System.out.println(ss);
		
		if(ss == null)
		{
			System.out.println("going towards failure");
			return mapping.findForward("failure");
			
		}
		
		
		System.out.println("towards success");
		return mapping.findForward("success");
		*/
		
		return mapping.findForward("success");

	}
}