/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.admin;

import java.util.UUID;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sanjivni.mail.Mail;

/** 
 * MyEclipse Struts
 * Creation date: 08-04-2013
 * 
 * XDoclet definition:
 * @struts.action path="/doctoradd" name="doctoraddForm" input="/admin/doctoradd.jsp" scope="request" validate="true"
 */
public class DoctoraddAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DoctoraddForm doctoraddForm = (DoctoraddForm) form;
		
		String _name = doctoraddForm.getName();
		String _department = doctoraddForm.getDepartment();
		String _email = doctoraddForm.getEmail();
		String _contactno = doctoraddForm.getContactno();
		String _designation = doctoraddForm.getDesignation();
		
		UUID idOne = UUID.randomUUID();
		String _uuid = idOne.toString();
		
		int status = AddDoc.adddoc(_name, _department, _email, _contactno, _designation,  _uuid);
		
		/*if(status>0)
		{
		
		Mail m = new Mail();
		
		m.setTo(_email);
		m.setSmtpServ("smtp.gmail.com");
		m.setSubject("Doctor's ID");
		m.setMessage("Your Unique ID is : "+_uuid);
		_email = m.getTo();
		m.setFrom("Sanjivni-Helth-Care");
		
		int result;


		result = m.sendMail();


		if(result == 0)
		{
		   
		 System.out.println(" Mail Successfully Sent to "+_email);*/
		 return mapping.findForward("success");
		/*}
		}
		String raxit = "Error fetching in email try again";
		request.getSession().setAttribute("Errorforgotpass", raxit);
		return mapping.findForward("failure");
		*/
	}
}