/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import com.raxit.hibernate.HibernateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-21-2013
 * 
 * XDoclet definition:
 * @struts.action path="/editDoct" name="editDoctForm" input="admin/editDoct.jsp" scope="request" validate="true"
 */
public class EditDoctAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		EditDoctForm editDoctForm = (EditDoctForm) form;// TODO Auto-generated method stub
		
		String _name = editDoctForm.getName();
		String _email = editDoctForm.getEmail();
		
		String _designation = editDoctForm.getDesignation();
		String _contactno = editDoctForm.getContactno();
		String _uuid = editDoctForm.getUuid();
		
		
		System.out.println(_name);
		System.out.println(_email);
		
		System.out.println(_designation);
		System.out.println(_contactno);
		System.out.println(_uuid);
		
		try{
			
			System.out.println("in edit portion");
			Session session = HibernateUtil.getSessionFactory().openSession();
			Transaction t = session.beginTransaction();
			Query q = session.createQuery("UPDATE DoctorPOJO set Name = :n , Email = :e , Designation = :d ,Contact_No= :c  where UUID='"+_uuid+"'");
			q.setString("n", _name);
			q.setString("d", _designation);
			q.setString("e", _email);
			
			q.setString("c", _contactno);
			int row=q.executeUpdate();
			  System.out.println("Number of row updated "+row);
			  session.getTransaction().commit();
			  return mapping.findForward("success");
			}
			catch (Exception e) {
				e.printStackTrace();
			}
			
			
			return mapping.findForward("failure");
		
		
	}
}