/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.raxit.hibernate.HibernateUtil;
import com.sanjivni.doctor.PrescriptionPOJO;

/** 
 * MyEclipse Struts
 * Creation date: 09-22-2013
 * 
 * XDoclet definition:
 * @struts.action path="/search_ClaimDetail2" name="search_ClaimDetail2Form" input="admin/search_ClaimDetail2.jsp" scope="request" validate="true"
 */
public class Search_ClaimDetail2Action extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Search_ClaimDetail2Form search_ClaimDetail2Form = (Search_ClaimDetail2Form) form;// TODO Auto-generated method stub
		
		
		String _search = search_ClaimDetail2Form.getSearch();
		String _value = search_ClaimDetail2Form.getValue();
		String status="IREJECT";
		
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction tr = session.beginTransaction();
		
		if(_search.equals("Name"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where name = :v AND status = :s");
			q.setString("v",_value);
			q.setString("s", status);
			
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Email"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where email = :v AND status = :s");
			q.setString("v",_value);
			q.setString("s", status);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Gender"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where gender = :v AND status = :s");
			q.setString("v",_value);
			q.setString("s", status);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Policy"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where policy = :v AND status = :s");
			q.setString("v",_value);
			q.setString("s", status);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Phoneno"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where phoneno = :v AND status = :s");
			q.setString("v",_value);
			q.setString("s", status);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("AdmitDate"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where admitdate = :v AND status = :s");
			q.setString("v",_value);
			q.setString("s", status);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("DischargeDate"))
		{
			Query q = session.createQuery( "From PrescriptionPOJO where dischargedate = :v AND status = :s");
			q.setString("v",_value);
			q.setString("s", status);
			
			List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		Query q = session.createQuery( "From PrescriptionPOJO where insuranceno = :v AND status = :s");
		q.setString("v",_value);
		q.setString("s", status);
		
		List<PrescriptionPOJO> check = (List<PrescriptionPOJO>)q.list();
		request.getSession().setAttribute("data", check);
		
		System.out.println("search complete...");
		
		
		return mapping.findForward("success");
		
		
		
	}
}