/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.raxit.hibernate.HibernateUtil;
import com.raxit.hibernate.PaitentPOJO;


/** 
 * MyEclipse Struts
 * Creation date: 09-23-2013
 * 
 * XDoclet definition:
 * @struts.action path="/search_AdmitedPaitent" name="search_AdmitedPaitentForm" input="admin/search_AdmitedPaitent.jsp" scope="request" validate="true"
 */
public class Search_AdmitedPaitentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Search_AdmitedPaitentForm search_AdmitedPaitentForm = (Search_AdmitedPaitentForm) form;// TODO Auto-generated method stub
		
		String _search = search_AdmitedPaitentForm.getSearch();
		String _value = search_AdmitedPaitentForm.getValue();
		String status = "1";
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction tr = session.beginTransaction();
		
		if(_search.equals("Admited"))
		{
			Query q = session.createQuery( "From PaitentPOJO where status != :v ");
			q.setString("v",status);
			
			
			
			List<PaitentPOJO> check = (List<PaitentPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Name"))
		{
			Query q = session.createQuery( "From PaitentPOJO where name = :v ");
			q.setString("v",_value);
			
			
			
			List<PaitentPOJO> check = (List<PaitentPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		
		else if(_search.equals("Email"))
		{
			Query q = session.createQuery( "From PaitentPOJO where email = :v ");
			q.setString("v",_value);
			
			
			
			List<PaitentPOJO> check = (List<PaitentPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		
		else if(_search.equals("Insuranceno"))
		{
			Query q = session.createQuery( "From PaitentPOJO where Insuranceno= :v ");
			q.setString("v",_value);
			
			
			
			List<PaitentPOJO> check = (List<PaitentPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("DOB"))
		{
			Query q = session.createQuery( "From PaitentPOJO where dob = :v ");
			q.setString("v",_value);
			
			
			
			List<PaitentPOJO> check = (List<PaitentPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Policy"))
		{
			Query q = session.createQuery( "From PaitentPOJO where Policy = :v ");
			q.setString("v",_value);
			
			
			
			List<PaitentPOJO> check = (List<PaitentPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		else if(_search.equals("Gender"))
		{
			Query q = session.createQuery( "From PaitentPOJO where gender = :v ");
			q.setString("v",_value);
			
			
			
			List<PaitentPOJO> check = (List<PaitentPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		}
		//else if(_search.equals("Insuranceno"))
		
			Query q = session.createQuery( "From PaitentPOJO where phoneno= :v ");
			q.setString("v",_value);
			
			
			
			List<PaitentPOJO> check = (List<PaitentPOJO>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
		
	}
}