/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package raxit.attempts;

import java.io.File;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.upload.FormFile;

import com.mysql.jdbc.Blob;

/** 
 * MyEclipse Struts
 * Creation date: 08-22-2013
 * 
 * XDoclet definition:
 * @struts.form name="imgattemptForm"
 */
public class ImgattemptForm extends ActionForm {
	/*
	 * Generated Methods
	 */
	
	private String name=null;
	private File content=null;
	

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public File getContent() {
		return content;
	}

	public void setContent(File content) {
		this.content = content;
	}

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		 /* ActionErrors errors = new ActionErrors();
	        if(content.getFileSize() == 0)
	             errors.add("uploadedFile", new ActionMessage("errors.file.notselected"));
	        if(errors.isEmpty()){
	            if(!content.getContentType().equalsIgnoreCase("image/jpeg") && !content.getContentType().equalsIgnoreCase("image/jpg")
	            && !content.getContentType().equalsIgnoreCase("image/pjpeg"))
	                errors.add("uploadedFile", new ActionMessage("errors.file.type", content.getFileName(),content.getContentType()));
	            if(content.getFileSize() > 50000)
	                errors.add("uploadedFile", new ActionMessage("errors.file.size",content.getFileName(),content.getFileSize()));
	        }*/
	        //return errors;
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}
}