/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;

import com.raxit.hibernate.AppointmentsPOJO;
import com.raxit.hibernate.HibernateUtil;
import com.sanjivni.doctor.PrescriptionPOJO;
import com.sanjivni.struts.form.AppointmentHistoryForm;

/** 
 * MyEclipse Struts
 * Creation date: 10-09-2013
 * 
 * XDoclet definition:
 * @struts.action path="/appointmentHistory" name="appointmentHistoryForm" input="/paitent/appointmentHistory.jsp" scope="request" validate="true"
 */
public class AppointmentHistoryAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AppointmentHistoryForm appointmentHistoryForm = (AppointmentHistoryForm) form;// TODO Auto-generated method stub
		
		HttpSession paitent = request.getSession();
		String ino = (String)paitent.getAttribute("Insuranceno");
		System.out.println(ino);
		
		org.hibernate.Session sess = HibernateUtil.getSessionFactory().openSession();
		org.hibernate.Transaction tr = sess.beginTransaction();
		
		Query q = sess.createQuery( "From AppointmentsPOJO where insuranceno = :i");
		q.setString("i",ino);
		
		List<AppointmentsPOJO> check = (List<AppointmentsPOJO>)q.list();
		request.getSession().setAttribute("data", check);
		
        tr.commit();
		
		
		return mapping.findForward("success");
		
		
		
	}
}