/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;


import com.sanjivni.mail.*;
import com.raxit.*;
import com.raxit.hibernate.PaitentPOJO;
import com.raxit.hibernate.HibernateUtil;

import com.sanjivni.struts.form.ForgotPassForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2013
 * 
 * XDoclet definition:
 * @struts.action path="/forgotPass" name="forgotPassForm" input="/paitent/forgotPass.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/paitent/paitentLogin.jsp" redirect="true"
 */
public class ForgotPassAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ForgotPassForm forgotPassForm = (ForgotPassForm) form;// TODO Auto-generated method stub
		String to = forgotPassForm.getEmail_id();
		String _uuid = null;
		String code = null;
		
		
		SessionFactory session = HibernateUtil.getSessionFactory();
		  Session sess = session.getCurrentSession();
		  
		  sess.beginTransaction();
		  	
	  		Query q  =	sess.createQuery("from PaitentPOJO where  email = :e");
	  		q.setString("e", to);
	  	
	  		
	  		List<PaitentPOJO> detail =(List<PaitentPOJO>)q.list();
		
	  		 sess.getTransaction().commit();
	  		 
	  		 if(detail.size()<=0)
	  		 {
	  			 //response.sendRedirect("LOGINFAILURE.jsp?e=Record not found");
	  			 return mapping.findForward("failure");
	  		 }
	  		 
	 		
	 		for(PaitentPOJO e1 : detail){
	 			code = e1.getUID();
	 			System.out.println(code);	 	
	 		}
	 		Mail m = new Mail();
			
			m.setTo(to);
			m.setSmtpServ("smtp.gmail.com");
			m.setSubject("reSetPassword");
			m.setMessage("http://raxit:8080/PaitentTrackmateSystem/paitent/resetPass.jsp?"+code);
			to = m.getTo();
			m.setFrom("Sanjivni-Helth-Care");
			
			int result;


			result = m.sendMail();


			if(result == 0)
			{
			   
			 System.out.println(" Mail Successfully Sent to "+to);
			 return mapping.findForward("success");
			}
			String raxit = "Error fetching in email try again";
			request.getSession().setAttribute("Errorforgotpass", raxit);
			return mapping.findForward("failure");
		
		
	}
}