/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.struts.action;

import java.security.MessageDigest;
import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

import com.raxit.hibernate.HibernateUtil;
import com.raxit.hibernate.PaitentPOJO;
import com.sanjivni.struts.form.PaitentLoginForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2013
 * 
 * XDoclet definition:
 * @struts.action path="/paitentLogin" name="paitentLoginForm" input="/paitent/paitentLogin.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/paitent/paitenthome.jsp" redirect="true"
 */
public class PaitentLoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PaitentLoginForm paitentLoginForm = (PaitentLoginForm) form;// TODO Auto-generated method stub
		
		
		String name = null;
		String email = null;
		String gender =null;
		String dob = null;
		String policy = null;
		String insuranceno = null;
		String idproof = null;
		String value = null;
		String phoneno = null;
		//String expiredate = null;
		
		
		String _login = paitentLoginForm.getLoginid();
		String _passwd = paitentLoginForm.getPasswd();
		
		String pass1 = null;
		
		try
		{
		MessageDigest md=MessageDigest.getInstance("MD5");
		String input=_passwd;
		md.update(input.getBytes());
		byte[] output=md.digest();
		MD5password sd = new MD5password();
		pass1 = sd.bytesToHex(output);
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}
		
		
		SessionFactory session = HibernateUtil.getSessionFactory();
		  Session sess = session.getCurrentSession();
		  
		  sess.beginTransaction();
		  	
	  		Query q  =	sess.createQuery("from PaitentPOJO where  email = :n and pass = :p");
	  		q.setString("n", _login);
	  		q.setString("p", pass1);
	  		
	  		List<PaitentPOJO> detail =(List<PaitentPOJO>)q.list();
	  		sess.getTransaction().commit();
		
	  		for(PaitentPOJO heli1 : detail)
	  		{
	  			name = heli1.getName();
	  			email = heli1.getEmail();
	  			gender = heli1.getGender();
	  			dob = heli1.getDob();
	  			phoneno = heli1.getPhoneno();
	  			idproof = heli1.getIdproof();
	  			value = heli1.getValue();
	  			policy = heli1.getPolicy();
	  			insuranceno = heli1.getInsuranceno();
	  			  			
	  		}
	  		HttpSession paitent = request.getSession();
		     if(detail.size()>0)
		     {
		    	paitent.setAttribute("Name", name);
		    	paitent.setAttribute("Email",email);
		    	paitent.setAttribute("DOB",dob );
		    	paitent.setAttribute("Insuranceno",insuranceno );
		    	paitent.setAttribute("Policy",policy );
		    	paitent.setAttribute("Gender",gender );
		        paitent.setAttribute("IdProof",idproof );
		    	paitent.setAttribute("Value",value );
		    	paitent.setAttribute("Phoneno", phoneno);
		    	 return mapping.findForward("success");
		     }
		
		
		    
				System.out.println("Loginerror");
				return mapping.findForward("failure");
		
		
	}
}