/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sanjivni.struts.action;

import java.security.MessageDigest;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;

import com.raxit.hibernate.HibernateUtil;
import com.sanjivni.struts.form.ResetPassForm;

/** 
 * MyEclipse Struts
 * Creation date: 07-31-2013
 * 
 * XDoclet definition:
 * @struts.action path="/resetPass" name="resetPassForm" input="/paitent/resetPass.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/paitent/paitentLogin.jsp" redirect="true"
 */
public class ResetPassAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		ResetPassForm resetPassForm = (ResetPassForm) form;// TODO Auto-generated method stub
		String _newpasswd = resetPassForm.getNewpass();
		String _conformnewpass = resetPassForm.getCnpass();
		String code = (String) request.getSession().getAttribute("Code");
		String p1 = null;
		String p2 = null;
		
		try
		{
		MessageDigest md=MessageDigest.getInstance("MD5");
		String input=_newpasswd;
		md.update(input.getBytes());
		byte[] output=md.digest();
		MD5password sd = new MD5password();
		p1=sd.bytesToHex(output);
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}
		
		try
		{
		MessageDigest md=MessageDigest.getInstance("MD5");
		String input=_conformnewpass;
		md.update(input.getBytes());
		byte[] output=md.digest();
		MD5password sd = new MD5password();
		p2=sd.bytesToHex(output);
		}
		catch(Exception e)
		{
			System.out.println(e.getMessage());
		}
		
		
		
		
		
		System.out.println(code);
		
		try
		{
			System.out.println("updating....!!");
		SessionFactory session1 = HibernateUtil.getSessionFactory();
		Session sess = session1.getCurrentSession();
		String update ="update PaitentPOJO set pass = :p, cpass = :cp where uid = :u";
		sess.beginTransaction();
		Query q = sess.createQuery(update);
		q.setString("p", p1);
		q.setString("cp", p2);
		q.setString("u", code);
		 int row=q.executeUpdate();
		  System.out.println("Number of row updated "+row);
		
		sess.getTransaction().commit();
		System.out.println("Done..!");
		return mapping.findForward("success");
		}
		catch(Exception e)
		{
			e.printStackTrace();
		}
		
		return mapping.findForward("failure");
	}
}