/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.insurance.table;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 08-18-2013
 * 
 * XDoclet definition:
 * @struts.action path="/insuranceTable" name="insuranceTableForm" input="/insurance_table/insuranceTable.jsp" scope="request" validate="true"
 */
public class InsuranceTableAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InsuranceTableForm insuranceTableForm = (InsuranceTableForm) form;// TODO Auto-generated method stub
		String msg = "hey watch it";
		String _name = insuranceTableForm.getName();
		String _email = insuranceTableForm.getEmail();
		String _phoneno = insuranceTableForm.getPhoneno();
		String _address =insuranceTableForm.getAddress();
		String _gender = insuranceTableForm.getGender();
		String _dob = insuranceTableForm.getDob();
		String _idproof = insuranceTableForm.getIdproof();
		String _value = insuranceTableForm.getValue();
		String _insuranceno = insuranceTableForm.getInsuranceno();
		String _expdate = insuranceTableForm.getExpdate();
		String _policy = insuranceTableForm.getPolicy();
		
	
		
		
		boolean me = RistrictValidation.Validate(_insuranceno, _policy);
		if(me==true)
		{
		
		int status = DateEntryInsert.Insert(_name, _email, _phoneno ,_address , _gender , _dob , _idproof ,_value , _policy , _insuranceno, _expdate);
		
		if(status>0)
		{
			return mapping.findForward("success");
		}
		}
		 
		return mapping.findForward("failure");
	}
}