/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.insurance.table;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

import com.insurance.table.Search_viewDataForm;
import com.raxit.hibernate.HibernateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-18-2013
 * 
 * XDoclet definition:
 * @struts.action path="/search_viewData" name="search_viewDataForm" input="insurance_table/search_viewData.jsp" scope="request" validate="true"
 */
public class Search_viewDataAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Search_viewDataForm search_viewDataForm = (Search_viewDataForm) form;// TODO Auto-generated method stub
		
		String _search = search_viewDataForm.getSearch();
		String _value = search_viewDataForm.getValue();
		
		//String policy = null;
		System.out.println(_search);
		System.out.println(_value);
		
		HttpSession insurance = request.getSession();
		String policy = (String)insurance.getAttribute("Admin");
		
		Session session = HibernateUtil.getSessionFactory().openSession();
		Transaction tr = session.beginTransaction();
		//String qry = "From InsurancePojo where InsuranceNo = :v";
		 //InsuranceNo
		if(_search.equals("Email"))
		{
			Query q = session.createQuery( "From InsurancePojo where Email = :v AND Policy =:p");
			q.setString("v",_value);
			q.setString("p",policy);
			
			List<InsurancePojo> check = (List<InsurancePojo>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			
			
		}
		else if(_search.equals("Name"))
		{
			Query q = session.createQuery( "From InsurancePojo where Name = :v AND Policy =:p");
			q.setString("v",_value);
			q.setString("p",policy);
			
			List<InsurancePojo> check = (List<InsurancePojo>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			 
		}
		
		else if(_search.equals("DOB"))
		{
			Query q = session.createQuery( "From InsurancePojo where DOB = :v AND Policy =:p");
			q.setString("v",_value);
			q.setString("p",policy);
			
			List<InsurancePojo> check = (List<InsurancePojo>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			 
		}
		else if(_search.equals("Policy"))
		{
			Query q = session.createQuery( "From InsurancePojo where Policy = :v AND Policy =:p");
			q.setString("v",_value);
			q.setString("p",policy);
			
			List<InsurancePojo> check = (List<InsurancePojo>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			 
		}
		else if(_search.equals("Gender"))
		{
			Query q = session.createQuery( "From InsurancePojo where Gender = :v AND Policy =:p");
			q.setString("v",_value);
			q.setString("p",policy);
			
			List<InsurancePojo> check = (List<InsurancePojo>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			 
		}
		else if(_search.equals("ExpireDate"))
		{
			Query q = session.createQuery( "From InsurancePojo where ExpireDate = :v AND Policy =:p");
			q.setString("v",_value);
			q.setString("p",policy);
			
			List<InsurancePojo> check = (List<InsurancePojo>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
			 
		}
		
		Query q = session.createQuery( "From InsurancePojo where Insuranceno = :v AND Policy =:p");
		q.setString("v",_value);
		q.setString("p",policy);
		
		List<InsurancePojo> check = (List<InsurancePojo>)q.list();
		request.getSession().setAttribute("data", check);
		
		System.out.println("search complete...");
		
		
		return mapping.findForward("success");
		
		
		
	}
}